### ISSUE TITLE
Feature Request: output to csv

### ISSUE THREAD

**Issue by ppival** [opencultureconsulting/openrefine-batch#3]
Would it be possible to offer the user a choice of outputting to csv in addition to tsv?

**Comment by felixlohmeier** [comment]
Hi Paul, Yes, of course. I am going to refactor the whole openrefine-batch tool next month (November 2017) in python and will then add more options (export to all formats openrefine currently supports, including templating). The export format is currently hard-coded.

**Comment by felixlohmeier** [comment]
No one wants to wait... I did a quick update to the existing shell-script :-).

Please download and test the new version to a blank directory:
`wget https://github.com/felixlohmeier/openrefine-batch/raw/master/openrefine-batch.sh && chmod +x openrefine-batch.sh`

You can now specify csv as export format with additional option `-e csv`

example:
```
./openrefine-batch.sh \
-a examples/powerhouse-museum/input/ \
-b examples/powerhouse-museum/config/ \
-c examples/powerhouse-museum/output/ \
-e csv \
-f tsv \
-i processQuotes=false \
-i guessCellValueTypes=true \
-RX

```
Please close the issue if it works for you.

**Comment by ppival** [comment]
Fantastic, thanks so much! Successfully output an xlsx to both csv and xlsx
