### ISSUE TITLE
safe cleanup handler

### ISSUE THREAD

**Issue by jackyq2015** [opencultureconsulting/openrefine-batch#4]
For main script clean up, it would be nice to put into a function and hook the signal to capture the unexpected exit/terminate:
https://www.ibm.com/developerworks/aix/library/au-usingtraps/index.html

**Comment by felixlohmeier** [comment]
thx @jackyq2015, i will keep that in mind for the next update (sometime in November)

**Comment by felixlohmeier** [comment]
hi @jackyq2015, is this what you meant? https://github.com/opencultureconsulting/openrefine-batch/commit/978344a55cdc950f4547de165041736ffc7a2e53

**Comment by jackyq2015** [comment]
@felixlohmeier instead of:
`trap cleanup EXIT`
should be something like this:
`trap cleanup SIGNHUP SIGINT SIGQUIT SIGTERM`

The idea is to capture all the the abnormal exit of your application for any reason(manually terminate, your script failed and OR itself failed etc). You would like an ensured clearnup to be executed no matter what.

**Comment by felixlohmeier** [comment]
thx @jackyq2015, I've got it!
