### ISSUE TITLE
zip or tar.gz archives Import not working

### ISSUE THREAD

**Issue by PSESEB** [opencultureconsulting/openrefine-batch#5]
The description says that it is possible to import multiple files as a project via zip or tar.gz archives.
While that is true for accessing open refine via browser, it is not true for this batch script. The python client that is used doesn't support archive imports. You get an python key error caused (I guess) by the non existence of the key 'zip' or 'tar.gz' in the [refine.py](https://github.com/opencultureconsulting/openrefine-client/blob/master/refine.py) file:
```
def create_project(options):
    """Create a new project from options.create file."""
    # general defaults are defined in google/refine/refine.py new_project
    # additional defaults for each file type
    defaults = {}
    defaults['xml'] = { 'project_format' : 'text/xml', 'recordPath' : 'record' }
    defaults['csv'] = { 'project_format' : 'text/line-based/*sv', 'separator' : ',' }
    defaults['tsv'] = { 'project_format' : 'text/line-based/*sv', 'separator' : '\t' }
    defaults['line-based'] = { 'project_format' : 'text/line-based', 'skipDataLines' : -1 }
    defaults['fixed-width'] = { 'project_format' : 'text/line-based/fixed-width', 'headerLines' : 0 }
    defaults['json'] = { 'project_format' : 'text/json', 'recordPath' : ('_', '_') }
    defaults['xls'] = { 'project_format' : 'binary/text/xml/xls/xlsx', 'sheets' : 0 }
    defaults['xlsx'] = { 'project_format' : 'binary/text/xml/xls/xlsx', 'sheets' : 0 }
    defaults['ods'] = { 'project_format' : 'text/xml/ods', 'sheets' : 0 }
```
So I am not sure if this issue is in the right place here, since the problem lies in the python client. Would be nice though to access this feature.

**Comment by felixlohmeier** [comment]
It should work if you specify the format of the archived files. Example:

zip archive containing a tsv file:
```
[22:41 felix ~/.../openrefine/openrefine-batch (master *%)]$ ls examples/test/input/
phm-collection.zip
```

command (with option -f):
```
./openrefine-batch.sh \
-a examples/test/input/ \
-b examples/test/config/ \
-c examples/test/output/ \
-f tsv \
-i processQuotes=false \
-i guessCellValueTypes=true \
-RX
```

Hope this helps!

**Comment by PSESEB** [comment]
I had a little misunderstanding about the -f option. 
Works just fine if you specify the format of the files in the archive.
Thanks!
